# Setup
title:        cuke_displayer
tagline:      "Cuke Displayer"
baseurl:      ""
include:      ['_cukes']
logo:         "assets/colours1.png"

# About/contact
author:
  name:       Frameworkium Team
  url:        https://github.com/Frameworkium

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
